# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cnsctl < Formula
  desc "CLI for generating validated GPU-accelerated Kubernetes configurations"
  homepage "https://github.com/mchmarny/cloud-native-stack"
  version "0.26.6"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mchmarny/cloud-native-stack/releases/download/v0.26.6/cnsctl_0.26.6_darwin_amd64.tar.gz"
      sha256 "cf65a633cfe394d8e30e41484ed26519fbac8fdbaa741ecd95272a745ad01cb0"

      def install
        bin.install "cnsctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mchmarny/cloud-native-stack/releases/download/v0.26.6/cnsctl_0.26.6_darwin_arm64.tar.gz"
      sha256 "851dd13a15511a2ce3852f284f993507155b8364ef4b8408fdcc036b48c6659f"

      def install
        bin.install "cnsctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mchmarny/cloud-native-stack/releases/download/v0.26.6/cnsctl_0.26.6_linux_amd64.tar.gz"
      sha256 "82908f4752a73f0a0918cc3adcc32cd77d34be0923792ec7f13eb40ad6ec7f09"
      def install
        bin.install "cnsctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mchmarny/cloud-native-stack/releases/download/v0.26.6/cnsctl_0.26.6_linux_arm64.tar.gz"
      sha256 "6b1d5056dff74d6dd2ff3a4e75917b796ad7a406b08ce9603214eac4b870caa4"
      def install
        bin.install "cnsctl"
      end
    end
  end

  test do
    system "#{bin}/cnsctl", "version"
  end
end
